development:
  secret_key_base: 820c2f81380b1603078d6f2bf8472eaef22f4fb85b0916e1266cfbf6678deadaa0453cd0eaf246edbdc91e093b1808f3e29bda7e08420ff130facc76533723bd
  mailer: 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
test:
  secret_key_base: 7ff549acd585a687bcff0089eb0ef8fdbf3da7e8bd555456891b8c5bede25eed534e02cd288d2683ec3905d989d660b195ab1ee7594ce9977cef4e3e5a8cc33e

production:
  secret_key_base: 7d3335ff0a9a0609a4f56cf3e63572287fda6a9a2d94b6eeafd4da5fe2e268d7694f8d330bc3e9d588800b544249bdbddb95dc232cf65f70a5059fa5bef0403a
